name: Auto Sync External M3U File

on:
  # প্রতি ২০ মিনিট অন্তর এই ওয়ার্কফ্লোটি চলবে (UTC সময় অনুযায়ী)।
  schedule:
    - cron: '*/20 * * * *' 
  # আপনি চাইলে GitHub ওয়েবপেজ থেকে ম্যানুয়ালিও এটি চালাতে পারবেন।
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download the latest Tata.m3u
        # 'curl' কমান্ড ব্যবহার করে external URL থেকে ফাইলটি ডাউনলোড করা এবং 'Tata.m3u' নামে সেভ করা।
        run: |
          curl -sL "https://raw.githubusercontent.com/abusaeeidx/Mrgify-Tv/refs/heads/main/playlist.m3u" -o "Tata.m3u"
          
      - name: Check for changes and auto-commit
        # কমিটের জন্য ফাইলের নাম 'Tata.m3u' হিসেবে সেট করা।
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'Tata.m3u'
          commit_message: "Automatic update: Synced Tata.m3u from external source"
          commit_user_name: 'GitHub Action Bot'
          commit_user_email: 'action@github.com'
